export const DenyReasons = {
  MODULE_NAME_MISMATCH: "MODULE_NAME_MISMATCH",
  ACTOR_ROLE_MISSING: "ACTOR_ROLE_MISSING",
  DIRECT_EXECUTION_FORBIDDEN: "DIRECT_EXECUTION_FORBIDDEN",
  MODULE_CANNOT_REQUEST_COMMAND: "MODULE_CANNOT_REQUEST_COMMAND",
  CAPABILITY_REQUIRED: "CAPABILITY_REQUIRED",
  ROUTE_NOT_ALLOWED: "ROUTE_NOT_ALLOWED",
  BRIDGE_CAPABILITY_REQUIRED: "BRIDGE_CAPABILITY_REQUIRED",
  BRIDGE_NODE_NOT_AVAILABLE: "BRIDGE_NODE_NOT_AVAILABLE",
  BRIDGE_NODE_TRUST_DENIED: "BRIDGE_NODE_TRUST_DENIED",
  BRIDGE_PREFERRED_NODE_FORBIDDEN: "BRIDGE_PREFERRED_NODE_FORBIDDEN",
  BRIDGE_CAPABILITY_ELEVATION_FORBIDDEN: "BRIDGE_CAPABILITY_ELEVATION_FORBIDDEN",
  BRIDGE_DISPATCH_FAILED: "BRIDGE_DISPATCH_FAILED",
  RUNTIME_EXEC_NOT_ALLOWED_FROM_TERMINAL_MODULE: "RUNTIME_EXEC_NOT_ALLOWED_FROM_TERMINAL_MODULE",
  MODULE_BYPASS_ATTEMPT_DETECTED: "MODULE_BYPASS_ATTEMPT_DETECTED"
} as const;
