# VXSTATION TERMINAL SSH IMPORT SNAPSHOT
# generated_at: 2026-04-04T12:32:20Z

Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_ed25519_linklock_dell

Host 100.127.85.101
  HostName 100.127.85.101
  User t79
  Port 2222
  IdentityFile ~/.ssh/id_ed25519_linklock_dell

Host vyrdx-droplet
  HostName 134.199.231.7
  User root
  IdentityFile ~/.ssh/vyrdx_droplet_ed25519

Host vyrdon-prod
  HostName 134.199.231.7
  User root
  IdentityFile ~/.ssh/vyrdon_prod
